/// <reference types="cypress" />

import { contains } from "cypress/types/jquery"

describe('Tests for basic functionality of app RS-clone', () => {
  beforeEach(() => {
    cy.viewport(1600, 800)
  })
  it('Login form', () => {
    cy.visit('http://localhost:3000/')
    cy.log('Сheck that we are on the Main page')
    cy.log('Trying to find SingIn button...')
    cy.get('#login').should('have.text', 'Sing in')
    cy.log('Trying to find H1 with text "What this app can do?"...')
    cy.get('#login').click()
    cy.log('And we at the Login page...')
    cy.url().should('eq', 'http://localhost:3000/login')
    cy.log('Trying to find login form...')
    cy.get('#singIn').should('have.prop', 'tagName' ).should('eq', 'FORM')
    cy.log('Typing wrong login and password')
    cy.get('#email').type('Hello, World')
    cy.get('#password').type('Hello, World')
    cy.get('#confirmLogin').click()
    cy.log('And we still at the Login page...')
    cy.url().should('eq', 'http://localhost:3000/login')
    cy.log('Trying to find error message')
    cy.get('.swal2-popup').find('h2').should('have.text', 'Неправильный логин / пароль')
    cy.get('.swal2-confirm').click()
    cy.log('Typing correct login and password')
    cy.get('#email').clear()
    cy.get('#email').clear()
    cy.get('#email').clear()
    cy.get('#password').clear()
    cy.get('#password').type('1')
    cy.get('#email').type('nikola.balabanov@gmail.ru')
    cy.get('#confirmLogin').click()
    cy.log('Check if we at /boards')
    cy.url().should('eq', 'http://localhost:3000/boards')
    cy.log(`LocalStorage info =', ${localStorage.getItem('redux')}`)
    cy.get('h1').should('have.text', 'Your boards')
    cy.log('Trying to visit Main page, Edit page')
    cy.get('.main').click()
    cy.url().should('eq', 'http://localhost:3000/')
    cy.get('.edit').click()
    cy.url().should('eq', 'http://localhost:3000/editprofile')
    cy.log("Let's logout!")
    cy.get('.logout').click()
    cy.url().should('eq', 'http://localhost:3000/')
    cy.log('Сheck that we are on the Main page')
    cy.log('Trying to find SingIn button...')
    cy.get('#login').should('have.text', 'Sing in')
    cy.log('Trying to find H1 with text "What this app can do?"...')
    cy.log("Ok. That's work")
  })
  it('Checking board create, edit, delete...', () => {
    cy.visit('http://localhost:3000/')
    cy.log('Trying to find SingIn button...')
    cy.get('#login').should('have.text', 'Sing in')
    cy.log('Trying to find H1 with text "What this app can do?"...')
    cy.get('#login').click()
    cy.log('Typing correct login and password')
    cy.get('#email').clear()
    cy.get('#password').clear()
    cy.get('#password').type('1')
    cy.get('#email').type('nikola.balabanov@gmail.ru')
    cy.get('#confirmLogin').click()
    cy.log('Check if we at /boards')
    cy.url().should('eq', 'http://localhost:3000/boards')
    cy.contains('+ Add a new board').click()
    cy.get('#board-name').type('My favorite board')
    cy.get('#board-name').parent().parent().next().next().click()
    cy.get('.swal2-popup').find('h2').should('have.text', 'The board was successfuly created!')
    cy.get('.swal2-confirm').click()
    cy.log('Board rename...')
    cy.contains('My favorite board').parent().find('#editCard').click()
    cy.get('#board-name').type(' for ever!')
    cy.get('#board-name').parent().parent().next().next().click()
    cy.get('.swal2-popup').find('h2').should('have.text', 'Card info updated on server')
    cy.get('.swal2-confirm').click()
    cy.contains('My favorite board for ever!').parent().contains('Open').click({ force: true })
    cy.get('h2').should('have.text', 'My favorite board for ever!').next().should('have.text', '+ Add a new column')
    cy.visit('http://localhost:3000/boards')
    cy.contains('My favorite board for ever!').parent().find('#deleteCard').click()
    cy.contains('Confirm').click()
    cy.get('.swal2-popup').find('h2').should('have.text', 'Card Deleted')
    cy.get('.swal2-confirm').click()
  })
})
